/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardWorkspaceRouteRouteImport } from './routes/_dashboard/workspace/route'
import { Route as DashboardWorkspaceIndexRouteImport } from './routes/_dashboard/workspace/index'
import { Route as DashboardWorkspaceAccountRouteImport } from './routes/_dashboard/workspace/account'
import { Route as DashboardWorkspaceWorkspaceIdRouteRouteImport } from './routes/_dashboard/workspace/$workspaceId/route'
import { Route as DashboardWorkspaceWorkspaceIdIndexRouteImport } from './routes/_dashboard/workspace/$workspaceId/index'
import { Route as DashboardWorkspaceWorkspaceIdChannelChannelIdIndexRouteImport } from './routes/_dashboard/workspace/$workspaceId/channel/$channelId/index'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspaceRouteRoute = DashboardWorkspaceRouteRouteImport.update({
  id: '/_dashboard/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspaceIndexRoute = DashboardWorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardWorkspaceRouteRoute,
} as any)
const DashboardWorkspaceAccountRoute =
  DashboardWorkspaceAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => DashboardWorkspaceRouteRoute,
  } as any)
const DashboardWorkspaceWorkspaceIdRouteRoute =
  DashboardWorkspaceWorkspaceIdRouteRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => DashboardWorkspaceRouteRoute,
  } as any)
const DashboardWorkspaceWorkspaceIdIndexRoute =
  DashboardWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardWorkspaceWorkspaceIdRouteRoute,
  } as any)
const DashboardWorkspaceWorkspaceIdChannelChannelIdIndexRoute =
  DashboardWorkspaceWorkspaceIdChannelChannelIdIndexRouteImport.update({
    id: '/channel/$channelId/',
    path: '/channel/$channelId/',
    getParentRoute: () => DashboardWorkspaceWorkspaceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/workspace': typeof DashboardWorkspaceRouteRouteWithChildren
  '/workspace/$workspaceId': typeof DashboardWorkspaceWorkspaceIdRouteRouteWithChildren
  '/workspace/account': typeof DashboardWorkspaceAccountRoute
  '/workspace/': typeof DashboardWorkspaceIndexRoute
  '/workspace/$workspaceId/': typeof DashboardWorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/channel/$channelId': typeof DashboardWorkspaceWorkspaceIdChannelChannelIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/workspace/account': typeof DashboardWorkspaceAccountRoute
  '/workspace': typeof DashboardWorkspaceIndexRoute
  '/workspace/$workspaceId': typeof DashboardWorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/channel/$channelId': typeof DashboardWorkspaceWorkspaceIdChannelChannelIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/_dashboard/workspace': typeof DashboardWorkspaceRouteRouteWithChildren
  '/_dashboard/workspace/$workspaceId': typeof DashboardWorkspaceWorkspaceIdRouteRouteWithChildren
  '/_dashboard/workspace/account': typeof DashboardWorkspaceAccountRoute
  '/_dashboard/workspace/': typeof DashboardWorkspaceIndexRoute
  '/_dashboard/workspace/$workspaceId/': typeof DashboardWorkspaceWorkspaceIdIndexRoute
  '/_dashboard/workspace/$workspaceId/channel/$channelId/': typeof DashboardWorkspaceWorkspaceIdChannelChannelIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/todos'
    | '/workspace'
    | '/workspace/$workspaceId'
    | '/workspace/account'
    | '/workspace/'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/channel/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/todos'
    | '/workspace/account'
    | '/workspace'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/channel/$channelId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/todos'
    | '/_dashboard/workspace'
    | '/_dashboard/workspace/$workspaceId'
    | '/_dashboard/workspace/account'
    | '/_dashboard/workspace/'
    | '/_dashboard/workspace/$workspaceId/'
    | '/_dashboard/workspace/$workspaceId/channel/$channelId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TodosRoute: typeof TodosRoute
  DashboardWorkspaceRouteRoute: typeof DashboardWorkspaceRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/workspace': {
      id: '/_dashboard/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof DashboardWorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/workspace/': {
      id: '/_dashboard/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof DashboardWorkspaceIndexRouteImport
      parentRoute: typeof DashboardWorkspaceRouteRoute
    }
    '/_dashboard/workspace/account': {
      id: '/_dashboard/workspace/account'
      path: '/account'
      fullPath: '/workspace/account'
      preLoaderRoute: typeof DashboardWorkspaceAccountRouteImport
      parentRoute: typeof DashboardWorkspaceRouteRoute
    }
    '/_dashboard/workspace/$workspaceId': {
      id: '/_dashboard/workspace/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof DashboardWorkspaceWorkspaceIdRouteRouteImport
      parentRoute: typeof DashboardWorkspaceRouteRoute
    }
    '/_dashboard/workspace/$workspaceId/': {
      id: '/_dashboard/workspace/$workspaceId/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof DashboardWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof DashboardWorkspaceWorkspaceIdRouteRoute
    }
    '/_dashboard/workspace/$workspaceId/channel/$channelId/': {
      id: '/_dashboard/workspace/$workspaceId/channel/$channelId/'
      path: '/channel/$channelId'
      fullPath: '/workspace/$workspaceId/channel/$channelId'
      preLoaderRoute: typeof DashboardWorkspaceWorkspaceIdChannelChannelIdIndexRouteImport
      parentRoute: typeof DashboardWorkspaceWorkspaceIdRouteRoute
    }
  }
}

interface DashboardWorkspaceWorkspaceIdRouteRouteChildren {
  DashboardWorkspaceWorkspaceIdIndexRoute: typeof DashboardWorkspaceWorkspaceIdIndexRoute
  DashboardWorkspaceWorkspaceIdChannelChannelIdIndexRoute: typeof DashboardWorkspaceWorkspaceIdChannelChannelIdIndexRoute
}

const DashboardWorkspaceWorkspaceIdRouteRouteChildren: DashboardWorkspaceWorkspaceIdRouteRouteChildren =
  {
    DashboardWorkspaceWorkspaceIdIndexRoute:
      DashboardWorkspaceWorkspaceIdIndexRoute,
    DashboardWorkspaceWorkspaceIdChannelChannelIdIndexRoute:
      DashboardWorkspaceWorkspaceIdChannelChannelIdIndexRoute,
  }

const DashboardWorkspaceWorkspaceIdRouteRouteWithChildren =
  DashboardWorkspaceWorkspaceIdRouteRoute._addFileChildren(
    DashboardWorkspaceWorkspaceIdRouteRouteChildren,
  )

interface DashboardWorkspaceRouteRouteChildren {
  DashboardWorkspaceWorkspaceIdRouteRoute: typeof DashboardWorkspaceWorkspaceIdRouteRouteWithChildren
  DashboardWorkspaceAccountRoute: typeof DashboardWorkspaceAccountRoute
  DashboardWorkspaceIndexRoute: typeof DashboardWorkspaceIndexRoute
}

const DashboardWorkspaceRouteRouteChildren: DashboardWorkspaceRouteRouteChildren =
  {
    DashboardWorkspaceWorkspaceIdRouteRoute:
      DashboardWorkspaceWorkspaceIdRouteRouteWithChildren,
    DashboardWorkspaceAccountRoute: DashboardWorkspaceAccountRoute,
    DashboardWorkspaceIndexRoute: DashboardWorkspaceIndexRoute,
  }

const DashboardWorkspaceRouteRouteWithChildren =
  DashboardWorkspaceRouteRoute._addFileChildren(
    DashboardWorkspaceRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TodosRoute: TodosRoute,
  DashboardWorkspaceRouteRoute: DashboardWorkspaceRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
