/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardWorkspaceRouteRouteImport } from './routes/_dashboard/workspace/route'
import { Route as DashboardWorkspaceIndexRouteImport } from './routes/_dashboard/workspace/index'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspaceRouteRoute = DashboardWorkspaceRouteRouteImport.update({
  id: '/_dashboard/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspaceIndexRoute = DashboardWorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardWorkspaceRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/workspace': typeof DashboardWorkspaceRouteRouteWithChildren
  '/workspace/': typeof DashboardWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/workspace': typeof DashboardWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/_dashboard/workspace': typeof DashboardWorkspaceRouteRouteWithChildren
  '/_dashboard/workspace/': typeof DashboardWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/todos' | '/workspace' | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/todos' | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/todos'
    | '/_dashboard/workspace'
    | '/_dashboard/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TodosRoute: typeof TodosRoute
  DashboardWorkspaceRouteRoute: typeof DashboardWorkspaceRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/workspace': {
      id: '/_dashboard/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof DashboardWorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/workspace/': {
      id: '/_dashboard/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof DashboardWorkspaceIndexRouteImport
      parentRoute: typeof DashboardWorkspaceRouteRoute
    }
  }
}

interface DashboardWorkspaceRouteRouteChildren {
  DashboardWorkspaceIndexRoute: typeof DashboardWorkspaceIndexRoute
}

const DashboardWorkspaceRouteRouteChildren: DashboardWorkspaceRouteRouteChildren =
  {
    DashboardWorkspaceIndexRoute: DashboardWorkspaceIndexRoute,
  }

const DashboardWorkspaceRouteRouteWithChildren =
  DashboardWorkspaceRouteRoute._addFileChildren(
    DashboardWorkspaceRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TodosRoute: TodosRoute,
  DashboardWorkspaceRouteRoute: DashboardWorkspaceRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
